### ISSUE TITLE
Win10环境 安装失败

### ISSUE THREAD

**Issue by chasezcz** [GentleCP/UCAS-Helper#12]
win10 系统。

使用  `pip install -r requirements.txt `，缺少lib。
使用  `conda env create -f environment.yml`，找不到对应版本。

老版本还是可以的，新版本更新后就白搭了，希望尽快适配windows

**Comment by GentleCP** [comment]
你好，已经在最新版本中修复该问题，conda 由于后续没有使用，已经不支持，请用pip安装新的依赖包，由于windows下不支持config的交互式界面，因此请手动配置`user_config.ini`中的内容。
