### ISSUE TITLE
包导入错误

### ISSUE THREAD

**Issue by j1nse** [GentleCP/UCAS-Helper#17]
**Bug描述**
包导入错误

**自查**
在提交问题前，请先确认以下几点。
- 是否采用了最新的版本代码，检查自己采用的版本和github上版本是否一致
- 是
- 是否严格按照了步骤进行了部署，有没有遗漏的地方
- 是

**出现问题的功能**
- ucashelper.py

**具体问题**
ImportError: cannot import name 'Assesser' from 'UCASHelper.core'

**截图**
![image](https://user-images.githubusercontent.com/22301107/117131237-c6350400-add3-11eb-9b43-11ea7ef94c16.png)

**问题反馈时间**
问题提交后一般会在24小时内提供反馈，如果超时还没有，说明问题尚未解决或本人最近较忙没有时间处理，不过最终都会解决，请耐心等待。

**Comment by GentleCP** [comment]
你好，该错误原因是master分支代码改动导致，master分支已不再维护，请更换到`v2`分支后再执行， 通过命令：
```shell
git checkout  v2
```
如果因为本地有改动导致切换失败，可以用
```shell
git stash
```
命令暂存改动后，再重新进行切换操作。
