### ISSUE TITLE
用一句话描述遇到的问题

### ISSUE THREAD

**Issue by GuDa2021** [GentleCP/UCAS-Helper#27]
**Bug描述**
sep登录失败

**自查**
在提交问题前，请先确认以下几点。
- 是否采用了最新的版本代码，检查自己采用的版本和github上版本是否一致
- 是的
- 是否严格按照了步骤进行了部署，有没有遗漏的地方
- 是的

**出现问题的功能**
- sep登录失败

**具体问题**
login.py-[line:103] 【ERROR】 sep登录失败，请检查你的用户名和密码设置以及验证码输入是否正确！
经过验证，并非验证码的问题，难道SEP又更新了登陆算法？

**致谢**
非常感谢大佬的分享，秋季学期使用此工具节省了大量时间，非常感谢！

**Comment by GentleCP** [comment]
你估计是把用户信息填写到`settings.py`中了，修改到`conf.user_config.ini`即可

**Comment by GuDa2021** [comment]
已顺利解决，感谢大佬及时回复！
