### ISSUE TITLE
关于课件下载问题

### ISSUE THREAD

**Issue by ChangWinde** [GentleCP/UCAS-Helper#4]
大部分课件可以正常下载，但是有一部分课件出现不全的现象。
目前出现这种情况的课程有《信息论》和《模式识别》

**Comment by GentleCP** [comment]
能否提供sep课程网站上课件列表的截图，重点标出无法下载到本地的文件

**Comment by GentleCP** [comment]
> 大部分课件可以正常下载，但是有一部分课件出现不全的现象。
> 目前出现这种情况的课程有《信息论》和《模式识别》

能否提供sep课程网站上课件列表的截图，重点标出无法下载到本地的文件

**Comment by ChangWinde** [comment]
> > 大部分课件可以正常下载，但是有一部分课件出现不全的现象。
> > 目前出现这种情况的课程有《信息论》和《模式识别》
> 
> 能否提供sep课程网站上课件列表的截图，重点标出无法下载到本地的文件

![pic1](https://user-images.githubusercontent.com/32702054/95009642-2e611300-0656-11eb-9a96-49897b186660.png)
![pic2](https://user-images.githubusercontent.com/32702054/95009644-302ad680-0656-11eb-8f33-5e2d4db8cf92.png)

**Comment by GentleCP** [comment]
> > > 大部分课件可以正常下载，但是有一部分课件出现不全的现象。
> > > 目前出现这种情况的课程有《信息论》和《模式识别》
> > 
> > 
> > 能否提供sep课程网站上课件列表的截图，重点标出无法下载到本地的文件
> 
> ![pic1](https://user-images.githubusercontent.com/32702054/95009642-2e611300-0656-11eb-9a96-49897b186660.png)
> ![pic2](https://user-images.githubusercontent.com/32702054/95009644-302ad680-0656-11eb-8f33-5e2d4db8cf92.png)

我又尝试了一门课下课件的同步，发现所有内容都是可以同步的， 出现你这个问题。那这样的话，我本地自己测试应该没办法检查出问题了，建议你这样尝试一下：在同步资源的时候单独选择该项无法同步的资源尝试下载（先根据序号选择课程，再根据序号选择要同步下载的文件），看看是否能够下载。如果还是不行，不知道你是否可以提供你的个人sep账号给我测试检验问题原因，如果可以的话邮件私信给我。

**Comment by ChangWinde** [comment]
> > > > 大部分课件可以正常下载，但是有一部分课件出现不全的现象。
> > > > 目前出现这种情况的课程有《信息论》和《模式识别》
> > > 
> > > 
> > > 能否提供sep课程网站上课件列表的截图，重点标出无法下载到本地的文件
> > 
> > 
> > ![pic1](https://user-images.githubusercontent.com/32702054/95009642-2e611300-0656-11eb-9a96-49897b186660.png)
> > ![pic2](https://user-images.githubusercontent.com/32702054/95009644-302ad680-0656-11eb-8f33-5e2d4db8cf92.png)
> 
> 我又尝试了一门课下课件的同步，发现所有内容都是可以同步的， 出现你这个问题。那这样的话，我本地自己测试应该没办法检查出问题了，建议你这样尝试一下：在同步资源的时候单独选择该项无法同步的资源尝试下载（先根据序号选择课程，再根据序号选择要同步下载的文件），看看是否能够下载。如果还是不行，不知道你是否可以提供你的个人sep账号给我测试检验问题原因，如果可以的话邮件私信给我。

![image](https://user-images.githubusercontent.com/32702054/95010467-1f7d5f00-065c-11eb-9e3e-01bb70e8e253.png)
在进入课程后，看不到之前无法下载的课件

**Comment by GentleCP** [comment]
问题已解决，请使用2.0.3版本即可。
