### ISSUE TITLE
破解wifi账号报错“出现异常:设备未注册,请在ePortal上添加认证设备”

### ISSUE THREAD

**Issue by frong0824** [GentleCP/UCAS-Helper#6]
请问，破解wifi账号过程中报错“出现异常:设备未注册,请在ePortal上添加认证设备”，是什么问题呢。

**Comment by GentleCP** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        这种情况估计是设备没能接入校园网，将网络断开，先尝试在浏览器中登录，如果可行，再退出，运行破解
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                GentleCP
                            
                    
                        
                            
                                    574881148@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年11月7日 21:18，FRONG<notifications@github.com> 写道： 




请问，破解wifi账号过程中报错“出现异常:设备未注册,请在ePortal上添加认证设备”，是什么问题呢。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
