### ISSUE TITLE
conda环境下联网失败

### ISSUE THREAD

**Issue by calanquee** [GentleCP/UCAS-Helper#7]
python ucashelper.py assess
2020-12-01 17:46:54,770 - Assesser - ERROR:[网络连接失败，请确认你的网络环境后重试！]

**Comment by GentleCP** [comment]
> python ucashelper.py assess
> 2020-12-01 17:46:54,770 - Assesser - ERROR:[网络连接失败，请确认你的网络环境后重试！]

这与conda无关，是登陆接口出错，已经在2.0.5版本中修复，可以直接下载最新的版本或者如果直接用命令`git stash && git fetch --all && git merge && git stash pop` 更新（要有git）

**Comment by calanquee** [comment]
可以啦，感谢感谢！！！
